### ISSUE TITLE
not all the source code present

### ISSUE THREAD

**Issue by mbgg** [EspoTek/Labrador_bin#1]
I realized that at least no source code is present for:
Desktop_Interface/build_linux/libdfuprog/lib/libdfuprog-0.9.so

Please provide all the source code.

**Comment by EspoTek** [comment]
It's not in a publishable state, but here it is:
https://drive.google.com/open?id=0B7U0ulRLHf8ca3lLbmNLZkpTNVk

Note that Android libdfuprog uses a different main.c, dfu.c and build script.

**Comment by mbgg** [comment]
Thanks for the info, but I don't think this closes the issue. We would need to have the whole source code centralized and an easy way to compile it, otherwise it puts the burden really high to collaborate.

**Comment by mbgg** [comment]
Just realized that this issue is for the Labrador repository not for the binary one.

**Comment by EspoTek** [comment]
Sorry about that.  
I'm new to all of this.

Please see: https://github.com/EspoTek/Labrador/issues/8
I think that basically covers what you were talking about.

**Comment by EspoTek** [comment]
Leaving this one closed since it's the bin repo.  (Why do I have a bin repo??)
